### ISSUE TITLE
Trying to upload file in s3 bucket using putObject

### ISSUE THREAD

**Issue by SwethaMano3110** [xtyxtyx/minio-dart#43]
Am trying to upload document in aws s3 bucket using putObject  await minio.putObject(bucketname,"path",data,
          onProgress: (bytes){
            print('uploaded');
          }
      );

But getting the error below, anyone can help me with it

Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:53529/dart_sdk.js:5067:11)
    at Object.nullCheck (http://localhost:53529/dart_sdk.js:5394:30)
    at minio_client.MinioClient.new.getRequestUrl (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:1056:44)
    at minio_client.MinioClient.new.getBaseRequest (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:1044:22)
    at minio_client.MinioClient.new._request (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:999:28)
    at _request.next (<anonymous>)
    at runBody (http://localhost:53529/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:53529/dart_sdk.js:40621:7)
    at minio_client.MinioClient.new.[_request] (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:994:20)
    at minio_client.MinioClient.new.request (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:1022:43)
    at request.next (<anonymous>)
    at runBody (http://localhost:53529/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:53529/dart_sdk.js:40621:7)
    at minio_client.MinioClient.new.request (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:1021:20)
    at minio$.Minio.new.getBucketRegion (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:2233:41)
    at getBucketRegion.next (<anonymous>)
    at runBody (http://localhost:53529/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:53529/dart_sdk.js:40621:7)
    at minio$.Minio.new.getBucketRegion (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:2225:20)
    at minio_client.MinioClient.new._request (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:996:55)
    at _request.next (<anonymous>)
    at runBody (http://localhost:53529/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:53529/dart_sdk.js:40621:7)
    at minio_client.MinioClient.new.[_request] (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:994:20)
    at minio_client.MinioClient.new.request (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:1022:43)
    at request.next (<anonymous>)
    at runBody (http://localhost:53529/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:53529/dart_sdk.js:40621:7)
    at minio_client.MinioClient.new.request (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:1021:20)
    at minio_uploader.MinioUploader.new._uploadChunk (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:293:39)
    at _uploadChunk.next (<anonymous>)
    at runBody (http://localhost:53529/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:53529/dart_sdk.js:40621:7)
    at minio_uploader.MinioUploader.new.[_uploadChunk] (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:292:20)
    at minio_uploader.MinioUploader.new.addStream (http://localhost:53529/packages/minio/src/minio_uploader.dart.lib.js:246:56)
    at addStream.next (<anonymous>)
    at http://localhost:53529/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:53529/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:53529/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:53529/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:53529/dart_sdk.js:35969:17)
    at _Future.new.[_complete] (http://localhost:53529/dart_sdk.js:35809:25)
    at _StreamIterator.new.[_onData] (http://localhost:53529/dart_sdk.js:37895:34)
    at _RootZone.runUnaryGuarded (http://localhost:53529/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:53529/dart_sdk.js:33906:22)
    at _DelayedData.new.perform (http://localhost:53529/dart_sdk.js:37377:28)
    at _StreamImplEvents.new.handleNext (http://localhost:53529/dart_sdk.js:37487:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53529/dart_sdk.js:37235:16)
    at Object._microtaskLoop (http://localhost:53529/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:53529/dart_sdk.js:40714:13)
    at http://localhost:53529/dart_sdk.js:36191:9

**Comment by ImanHz** [comment]
possibly you have not specified the region or some other parameters in the minio initializations.

**Comment by shinriyo** [comment]
wired things...
